### PR TITLE
Create conda environment and build in develop mode

### PR DESCRIPTION
**Pull request by sandhujasmine**
Added environment.yml for creating a conda development environment.
Updated README.md to includes steps for making a conda environment and building py_gnome in develop mode using conda.

Tested on the Mac but unable to test on windows.

### CODE REVIEW

**Comment by sandhujasmine** [comment]
This does not automatically build oil_library so tests fail.
Need to create environment.yml for oil_library and build the oil_library as well before this works. Ideally the oil_library should be a separate package that gets conda installed.

**Comment by ChrisBarker-NOAA** [comment]
Yeah, we really should simply make oil_lib it's own project -- it would make a bunc hof this easier.

The trick was (is) that we were frequently updating the oil_lib and py_gnome in concert -- both needed to be upgraded at once, so it was nice to keep them in the same repo.

Maybe it's stabilized more now???

**Comment by ChrisBarker-NOAA** [comment]
@JamesMakela-NOAA: 

Could you take a look and see how this all fits in with your updated Anaconda instructions?

-CHB

**Comment by JamesMakela-NOAA** [comment]
@sandhujasmine, @ChrisBarker-NOAA,
Ok guys, I looked at this, and I see a lot of value in the environment.yml.
But I have restructured the README docs a bit, so I will need to merge these README changes with what we currently have next time I sync the GitHub.
For right now though, I will accept this pull.

**Comment by ChrisBarker-NOAA** [comment]
Great,

Thanks Jasmine!

**Comment by AmyMacFadyen** [comment]
Great to have you back, Jasmine :)

**Pull request merged**
